### ISSUE TITLE
Deferred action

### ISSUE THREAD

**Issue by olufjen** [olufjen/chess#20]
Create an action during planting procedures

**Comment by olufjen** [comment]
At present chessactions are created as part of the minimax search process.
When created the chessaction is given a AgamePiece, its reachable positions and the player who owns the piece.
Based on this the chessaction creates a possible move for this piece.

A deferred action can be created with

**Comment by olufjen** [comment]
The Problem object uses permutations to calculate other actions. It uses all constants in all positions of the preconditions and effects.
This is shown in the enclosed file.
[https://app.zenhub.com/files/137453363/7a0d9f6d-2626-4ac3-837b-aa3d85a38a1e/download](https://app.zenhub.com/files/137453363/7a0d9f6d-2626-4ac3-837b-aa3d85a38a1e/download)

**Comment by olufjen** [comment]
Castling and deferred actions:
OBS OBS: [occupies(WhiteKing,g1), OWNER(WhitePlayer,WhiteKing), PIECETYPE(WhiteKing,PAWN), BOARD(g1)]

**Comment by olufjen** [comment]
After White castling the white Rook has the following positions:
Piece name WhiteRook2
Piece position f1 X, Y (5, 0) wR f1 ROOK ActiveName R
Available positions
Position: h1 W X, Y (7, 0)
Position: g1 B X, Y (6, 0) Occupied by: WhiteKing
Position: f2 B X, Y (5, 1) Occupied by: WhitePawn6
Position: e1 B X, Y (4, 0)
Position: f3 W X, Y (5, 2) Occupied by: WhiteKnight2
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: f4 B X, Y (5, 3)
Position: c1 B X, Y (2, 0) Occupied by: WhiteBishop1
Position: f5 W X, Y (5, 4) Occupied by: BlackBishop1
Position: b1 W X, Y (1, 0)
Position: f6 B X, Y (5, 5) Occupied by: BlackKnight2
Position: a1 B X, Y (0, 0) Occupied by: WhiteRook1
Position: f7 W X, Y (5, 6) Occupied by: BlackPawn6
Position: f8 B X, Y (5, 7) Occupied by: BlackRook2
Removed positions
Position: h2 B X, Y (7, 1) Occupied by: WhitePawn8
Position: e1 B X, Y (4, 0)
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: c1 B X, Y (2, 0) Occupied by: WhiteBishop1
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: a1 B X, Y (0, 0) Occupied by: WhiteRook1
Position: h3 W X, Y (7, 2)
Position: h4 B X, Y (7, 3)
Position: h5 W X, Y (7, 4)
Position: h6 B X, Y (7, 5) Occupied by: BlackPawn8
Position: h7 W X, Y (7, 6)
Position: h8 B X, Y (7, 7)
Position: b1 W X, Y (1, 0)

All the h positions should not be there.

**Comment by olufjen** [comment]
Must clear deferred moves:

Caused by: java.lang.NullPointerException
	at no.chess.web.model.game.AChessProblemSolver.deferredMove(AChessProblemSolver.java:817)
	at no.chess.web.model.game.AChessProblemSolver.planProblem(AChessProblemSolver.java:852)

**Comment by olufjen** [comment]
**Too many removed positions:**
Piece name WhiteRook2
Piece position f1 X, Y (5, 0) wR f1 ROOK ActiveName R
Available positions
Position: h1 W X, Y (7, 0)
Position: g1 B X, Y (6, 0) Occupied by: WhiteKing
Position: f2 B X, Y (5, 1) Occupied by: WhitePawn6
Position: e1 B X, Y (4, 0)
Position: f3 W X, Y (5, 2) Occupied by: WhiteKnight2
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: f4 B X, Y (5, 3)
Position: c1 B X, Y (2, 0) Occupied by: WhiteBishop1
Position: f5 W X, Y (5, 4) Occupied by: BlackBishop1
Position: b1 W X, Y (1, 0)
Position: f6 B X, Y (5, 5) Occupied by: BlackKnight2
Position: a1 B X, Y (0, 0) Occupied by: WhiteRook1
Position: f7 W X, Y (5, 6) Occupied by: BlackPawn6
Position: f8 B X, Y (5, 7) Occupied by: BlackRook2
Removed positions
Position: g1 B X, Y (6, 0) Occupied by: WhiteKing
Position: f2 B X, Y (5, 1) Occupied by: WhitePawn6
Position: f3 W X, Y (5, 2) Occupied by: WhiteKnight2
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: c1 B X, Y (2, 0) Occupied by: WhiteBishop1
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: a1 B X, Y (0, 0) Occupied by: WhiteRook1
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: d1 W X, Y (3, 0) Occupied by: WhiteQueen
Position: e1 B X, Y (4, 0)
Position: b1 W X, Y (1, 0)
Position: f4 B X, Y (5, 3)
Position: f5 W X, Y (5, 4) Occupied by: BlackBishop1
Position: f6 B X, Y (5, 5) Occupied by: BlackKnight2
Position: f7 W X, Y (5, 6) Occupied by: BlackPawn6
Position: f8 B X, Y (5, 7) Occupied by: BlackRook2

**Comment by olufjen** [comment]
12.04.21:
Caused by: java.lang.NullPointerException
	at no.chess.web.model.game.AChessProblemSolver.deferredMove(AChessProblemSolver.java:821)
	at no.chess.web.model.game.AChessProblemSolver.planProblem(AChessProblemSolver.java:852)

12.04.21 solved

**Comment by olufjen** [comment]
The black castle disappeared:

![blackcastling.PNG](https://images.zenhubusercontent.com/5db2e35fa7e95f000179f1d4/8b9e6439-ffa3-41cc-b78b-7ed725e157ba)

**Comment by olufjen** [comment]
Create diagrams for the default part of the checkMovenumber method !!!

**Comment by olufjen** [comment]
OBS The castling move notation here:


![castlingmove.PNG](https://images.zenhubusercontent.com/5db2e35fa7e95f000179f1d4/9467e5ff-2855-4d3e-bfde-b566a65a235f)

**Comment by olufjen** [comment]
After successful castling:

Caused by: java.lang.NullPointerException
	at no.chess.web.model.PlayGame.proposeMove(PlayGame.java:307)
	at no.chess.web.server.resource.RapporterChessStartServerResourceHTML.storeChess(RapporterChessStartServerResourceHTML.java:808)

**Comment by olufjen** [comment]
A "no-move" after the castling:

![castling030521.PNG](https://images.zenhubusercontent.com/5db2e35fa7e95f000179f1d4/5c686222-488f-408f-a8a2-652be8f5051e)

There should be a move after Bishop Bf5
