### ISSUE TITLE
Castling

### ISSUE THREAD

**Issue by olufjen** [olufjen/chess#56]
Problem with castling:
Occupies wrong position: http://www.co-ode.org/ontologies/ont.owl#e1 e1 g1
setPieces: Name of piece: WhiteKing Name of chess piece: K wK
Occupies wrong position: http://www.co-ode.org/ontologies/ont.owl#h1 h1 f1
setPieces: Name of piece: WhiteRook2 Name of chess piece: R wR

**Comment by olufjen** [comment]
0" | "-" | "-"
"1" | "d4" | "d5"
"2" | "c4" | "Nf6"
"3" | "Nc3" | "e6"
"4" | "Nf3" | "Bd6"
"5" | "cxd5" | "exd5"
"6" | "e3" | "o-o"
"7" | "Bd3" | "Nc6"
"8" | "o-o" | "h6"
"9" | "Qb3" | "Be6"
"10" | "Nxd5" | "Nxd5"
"11" | "Be4" | "Nb4"
"12" | "Bxd5" | "Nxd5"
"13" | "Qb5" | "a6"
"14" | "Qb3" | "c6"
"15" | "Qc4" | "Qc7"
"16" | "Qb3" | "Bxh2"
"17" | "Nxh2" | "Re8"
"18" | "Qc4" | "Bd7"
"19" | "Qc5" | "Re4"
"20" | "Qxf8" | "Kxf8"
"21" | "a3" | "-"
Caused by: java.lang.NullPointerException
	at no.games.chess.planning.ChessLevel.<init>(ChessLevel.java:61)
	at no.games.chess.planning.ChessGraphPlanAlgorithm.initialPlanningGraph(ChessGraphPlanAlgorithm.java:262)
	at no.games.chess.planning.ChessGraphPlanAlgorithm.graphPlan(ChessGraphPlanAlgorithm.java:49)
	at no.chess.web.model.game.AChessProblemSolver.planProblem(AChessProblemSolver.java:1331)
